### ISSUE TITLE
Module xx.dll failed to load "xx.dll"

### ISSUE THREAD

**Issue by spellman001** [0671/RedisModules-ExecuteCommand-for-Windows#3]
在我的测试环境win10 以及 2008 r2 上从 通过redis-cli执行module load xx.dll 均显示无法加载模块，请问这个利用是有什么限制吗

**Comment by 0671** [comment]
1、报错截图看一下
2、**redis-server**运行的系统是win还是linux，版本是多少？

**Comment by spellman001** [comment]
方便加一下吗

**Comment by spellman001** [comment]
我在4.0.14和5.0.14，5.0.10上测试过均无法加载模块

**Comment by spellman001** [comment]
环境是win的

**Comment by 0671** [comment]
截图我看下，报错原因

**Comment by spellman001** [comment]
![image](https://user-images.githubusercontent.com/43229146/140650786-c02ef5bd-1bc1-40f0-b496-897983446ca0.png)

**Comment by spellman001** [comment]
exp 是在redis的同级目录

**Comment by 0671** [comment]
exp.dll 放在和 redis-server.exe 同一个目录下

**Comment by spellman001** [comment]
是的 exp.dll 是和redis-server 同个目录下的

**Comment by 0671** [comment]
可以尝试重新编译dll。
![image](https://user-images.githubusercontent.com/28929714/140651949-59988b6f-4114-42a5-a9af-fd3843759f49.png)

**Comment by spellman001** [comment]
是的 我有尝试在vc2019 上从新编译过dll 但是任然无效，请问你运行的redis-server的系统环境是什么

**Comment by 0671** [comment]
win10，和我vs2017同一个机器
